if [ "$(tty)" = "/dev/tty1" ]; then
  _JAVA_AWT_WM_NONREPARENTING=1 MOZ_ENABLE_WAYLAND=1 XKB_DEFAULT_LAYOUT=de QT_WAYLAND_FORCE_DPI=96 QT_QPA_PLATFORM=wayland-egl CLUTTER_BACKEND=wayland SDL_VIDEODRIVER=wayland BEMENU_BACKEND=wayland exec sway
fi
